INSERT INTO Barangay (barangay_name, city_ID) 
SELECT barangay_name, city_ID FROM (
    SELECT 'Arena Blanco' as barangay_name, city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Ayala', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Baliwasan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Baluno', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Boalan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Bolong', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Buenavista', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Bunguiao', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Busay', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Cabaluay', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Cabatangan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Cacao', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Calabasa', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Calarian', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Camino Nuevo', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Campo Islam', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Canelar', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Capisan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Cawit', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Culianan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Curuan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Dita', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Divisoria', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Dulian (Upper Bunguiao)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Dulian (Lower Pasonanca)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Guisao', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Guiwan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Kasanyangan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'La Paz', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Labuan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lamisahan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Landang Gua', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Landang Laum', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lanzones', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lapakan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Latuan (Curuan)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Licomo', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Limaong', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Limpapa', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lubigan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lumayang', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lumbangan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Lunzuran', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Maasin', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Malagutay', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Mampang', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Manalipa', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Mangusu', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Manicahan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Mariki', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Mercedes', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Muti', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Pamucutan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Pangapuyan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Panubigan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Pasilmanta (Sacol Island)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Pasobolong', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Pasonanca', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Patalon', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Putik', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Quiniput', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Recodo', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Rio Hondo', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Salaan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'San Jose Cawa-cawa', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'San Jose Gusu', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'San Roque', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Sangali', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Santa Barbara', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Santa Catalina', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Santa Maria', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Santo Niño', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Sibulao (Caruan)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Sinubung', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Sinunoc', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tagasilay', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Taguiti', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Talabaan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Talisayan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Talon-talon', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Taluksangay', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tetuan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tictapul', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tigbalabag', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tigtabon', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tolosa', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tomas Claudio', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tugbungan', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tulungatung', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tumaga', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tumalutab', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Tumitus', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Victoria', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Vitali', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Zambowood', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Zone I (Poblacion)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Zone II (Poblacion)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Zone III (Poblacion)', city_ID FROM City WHERE city_name = 'Zamboanga City' UNION ALL
    SELECT 'Zone IV (Poblacion)', city_ID FROM City WHERE city_name = 'Zamboanga City'
) AS zamboanga_barangays;